### ISSUE TITLE
Adetailer not working

### ISSUE THREAD

**Issue by koodaesae** [steinhaug/stable-diffusion#1]
Hi, I believe with the new update to adetailer, the adetailer extension is not working. I get the following error.

```
[-] ADetailer: Invalid arguments passed to ADetailer.
    input: ()
    ADetailer disabled.
```

Also, with the update the controlnet settings in the adetailer extension seems to be missing in the UI

**Comment by steinhaug** [comment]
Didn't see this one. I have verified the install just now, everything runs including ADetailer and Controlnet.
